service: hola-mundo

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline

functions:
  hello-world:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET

