service: users-lamda-dynamodb

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline

functions:
  users-lamda-dynamodb:
    handler: handler.getTime
    events:
      - http:
          path: time
          method: GET

