service: users-lambda-dynamodb

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  get-users:
    handler: handler.getUsers
    events:
      - http:
          path: users
          method: GET